services:
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    restart: always
    shm_size: 2g

  app:
    build: .
    command: sh -c 'python visa.py'
    depends_on:
      - selenium
    volumes:
      - .:/app
