version: "3"
services:
  selenium-chrome:
    image: selenium/standalone-chrome:4.21.0
    container_name: selenium-chrome
    environment:
      - SE_SESSION_REQUEST_TIMEOUT=604800
      - SE_SESSION_MAP_TIMEOUT=604800
    ports:
      - "4444:4444"
